name: CI develop workflow

on:
  pull_request:
  push:
    branches:
#       - develop
      - feature/avalonia-ui

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Path: src/Socketpost.sln
      WinApp_Project_Path: src/Socketpost.DesktopApp/Socketpost.DesktopApp.csproj
      Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands for Nerdbank.GitVersioning to set version variables

    strategy:
      matrix:
        targetplatform: [x86, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
      - name: Use Nerdbank.GitVersioning to set version variables
        uses: aarnott/nbgv@v0.3
        with:
          setAllVars: true
          path: src/Socketpost.DesktopApp/

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # Publish the Windows Application
      - name: Build the Windows Application
        run: dotnet publish $env:WinApp_Project_Path -c $env:Configuration -o $env:BuildOutputPath -p:PublishSingleFile=true -r $env:TargetPlatform --self-contained true /p:useapphost=true
        env:
          Configuration: Debug
          TargetPlatform: win-${{ matrix.targetplatform }}
          BuildOutputPath: build/win-${{ matrix.targetplatform }}/

      # Upload the application package: https://github.com/marketplace/actions/upload-artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        env:
          Name: Socketpost-win-${{ matrix.targetplatform }}-${{ env.NBGV_SimpleVersion }}.${{ env.VersionHeight }}-beta
        with:
          name: ${{ env.Name }}
          path: build/win-${{ matrix.targetplatform }}/
